jobs:
  - name: job-os-release
    public: true
    plan:
      - task: show-os-release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine}
          run:
            path: cat 
            args: [/etc/passwd]


# fly -t tutorial set-pipeline -c 01_pipeline-show-os-release.yml -p show os-release
# fly -t tutorial unpause-pipeline -p job-os-release
# fly -t tutorial unpause-job --job task/job-name

## --job / -j
# fly -t tutorial watch --job pipeline_name/job-name


# fly tutorial trigger-job -j task/job-name -w

          #run:
            #path: date
            #args:
