---
resources:
  - name: concourse-jan-pipeline
    type: git
    source: {uri: "git@github.com:JanKraut/concourse-jan.git"}

jobs:
  - name: show-date-job
    plan:
      - get: concourse-jan-pipeline # get-resource name
        trigger: true
      - task: show-date-job
        #config:
        #  platform: linux
        #  image_resource:
        #    type: docker-image
        #    source: {repository: ubuntu}
        input_mapping:
          test: concourse-jan-pipeline
          #run:
          #  path: echo
          #  args: [hello world]
          #file: concourse-jan/tasks/test-pipeline-task.yml
        file: concourse-jan-pipeline/examples/hello-world.yml