---
resources:
  - name: concourse-jan-pipeline
    type: git
    source: {uri: "https://github.com/JanKraut/concourse-jan.git"}

jobs:
  - name: show-date-job
    plan:
      - get: concourse-jan-pipeline # get-resource name
        trigger: true
      - task: show-date-job
        #config:
        #  platform: linux
        #  image_resource:
        #    type: docker-image
        #    source: {repository: ubuntu}
        input_mapping:
          test-input: concourse-jan-pipeline
        output_mapping:
          name: ordner
        params:
          FILES: ordner
          #run:
          #  path: echo
          #  args: [hello world]
          #file: concourse-jan/tasks/test-pipeline-task.yml
        file: concourse-jan-pipeline/tasks/generate-files-task.yml

      - task: show-files
        input_mapping:
          test: concourse-jan-pipeline123
          name: ordner
        params:
          FILES: ordner
          #run:
          #  path: echo
          #  args: [hello world]
          #file: concourse-jan/tasks/test-pipeline-task.yml
        file: concourse-jan-pipeline/tasks/concourse-task.yml