---
resources:
  - name: concourse-jan
    type: git
    source: {uri: "git@github.com:JanKraut/concourse-jan.git"}

jobs:
  - name: test-pipeline-job
    plan:
      #- get: concourse-jan-pipeline # get-resource name
      - task: test-pipeline-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          input_mapping:
            test: test1
          #run:
          #  path: echo
          #  args: [hello world]
          file: concourse-jan/tasks/test-pipeline-task.yml
