---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu

params:
  NAME:

inputs:
  - name: concourse-jan-pipeline-git
outputs:
  - name: output

run:
  path: concourse-jan-pipeline-git/tasks/generate-date.sh
  args:
    - output/out.txt