---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu

params:
  NAME:

inputs:
  - name: concourse-jan-pipeline-git
outputs:
  - name: output

run:
  path: /bin/sh
  args:
    - concourse-jan-pipeline-git/example-pipe01/tasks/generate-date.sh
    - output/out.txt
