---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu

inputs:
  - name: concourse-jan-pipeline-git
  - name: message

run:
  path: /bin/sh
  args:
    - concourse-jan-pipeline-git/example-pipe01/tasks/print-date.sh
    - message/out.txt
