---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ubuntu

params:
  FILES:

inputs:
  - name: test-input

outputs:
  - name: output

run:
  path: test-input/tasks/generate-files.sh
  args: 
    - output/