---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ubuntu

params:
  FILES:

inputs:
  - name: concourse-jan

#outputs:
#  - name: output

run:
  path: tasks/show-files.sh
  args: 